# Generated by Django 4.1.7 on 2024-01-02 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('tc', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=100)),
                ('complaint_reason', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=150)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_code', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'çözüldü'), (2, 'iptal edildi'), (3, 'bekliyor')], default=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=500)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('ticket_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket_request')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Request_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='images/')),
                ('ticket_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket_request')),
            ],
        ),
    ]
